### ISSUE TITLE
OWID- Mapping with OGS integration data model

### ISSUE THREAD

**Issue by S-AI-F** [OpenGeoScales/ogs-data-exploration#64]
Mapping rules: https://docs.google.com/spreadsheets/d/1CnTpHjZZZepgJ1o1VuQUN61ZaLLRtM1OhZzJU9HCPaY/edit#gid=0

**Comment by S-AI-F** [comment]
@JinqiWANG66 
@linetonthat 

### Goal
The goal of this issue consists of testing ogs ghg emissions data model.
Outputs are:
- Filling the excel file for mapping information
- Mapping script
- mapped data in json format

### Mapping information

You are invited to map the dataset you are responsible of with the proposed data model in this file: https://docs.google.com/spreadsheets/d/1CnTpHjZZZepgJ1o1VuQUN61ZaLLRtM1OhZzJU9HCPaY/edit#gid=0

### Mapping script
The mapping script will be stored in **ogs-data-exploration/ghg-emissions/notebooks/your data source name/mapping_datasourcename**
Here is a script example for ammping gcp dataset:
https://github.com/OpenGeoScales/ogs-data-exploration/blob/main/notebooks/ghg-emissions/gcp/Mapping_GCP.ipynb

### Mapped data

Mapped data should be stored as json files in **ogs-data-exploration/ghg-emissions/data/your data source name/mapped/mapped_data_yorudatasourcename**

Here is an example of gcp mapped data: https://github.com/OpenGeoScales/ogs-data-exploration/tree/main/data/ghg-emissions/gcp/mapped

**Comment by linetonthat** [comment]
@S-AI-F 
@JinqiWANG66 

A few questions:
- Could you please confirm that the CO2 emissions must be expressed in MtC (and not MtCO2)?
- How should we handle values for Kosovo, as the country has no ISO code, as it's not recognized by all countries (cf. https://fr.wikipedia.org/wiki/Kosovo)? In the dataset, the pseudo ISO code is 'OWID_KOS".
- I don't understand in the Mapping script example why the total CO2 value is not part of the variables listed: is it because it's  at a higher level in the hierarchy that we need to create? Or is it because, it's supposed to be the sum of all the values from the subsector? Or is it because it should be added to the list of subsectors?
- In the OWID dataset, there is "trade_co2" which is an interesting variable, as it represents the CO2 emissions linked to commercial exchanges between countries. This helps assess consumption-based CO2 emissions ("consumption_co2"). Should "trade_co2" be one of the subsectors?
- Should we also stored results of calculations, or should these calculations be done within the API? For example, "consumption_co2" can be deduced from "co2" and "trade_co2".

**Comment by linetonthat** [comment]
@S-AI-F
@JinqiWANG66

* Should we also keep per capita CO2 emissions?

**Comment by S-AI-F** [comment]
> @S-AI-F
> @JinqiWANG66
> 
> A few questions:
> 
> * Could you please confirm that the CO2 emissions must be expressed in MtC (and not MtCO2)?
> * How should we handle values for Kosovo, as the country has no ISO code, as it's not recognized by all countries (cf. https://fr.wikipedia.org/wiki/Kosovo)? In the dataset, the pseudo ISO code is 'OWID_KOS".
> * I don't understand in the Mapping script example why the total CO2 value is not part of the variables listed: is it because it's  at a higher level in the hierarchy that we need to create? Or is it because, it's supposed to be the sum of all the values from the subsector? Or is it because it should be added to the list of subsectors?
> * In the OWID dataset, there is "trade_co2" which is an interesting variable, as it represents the CO2 emissions linked to commercial exchanges between countries. This helps assess consumption-based CO2 emissions ("consumption_co2"). Should "trade_co2" be one of the subsectors?
> * Should we also stored results of calculations, or should these calculations be done within the API? For example, "consumption_co2" can be deduced from "co2" and "trade_co2".

**Comment by S-AI-F** [comment]
> > @S-AI-F
> > @JinqiWANG66
> > A few questions:
> > 
> > * Could you please confirm that the CO2 emissions must be expressed in MtC (and not MtCO2)?
Mapped data should keppe the same units as data source. We only should mention the unit in the unit filed.
> > * How should we handle values for Kosovo, as the country has no ISO code, as it's not recognized by all countries (cf. https://fr.wikipedia.org/wiki/Kosovo)? In the dataset, the pseudo ISO code is 'OWID_KOS".
> > * I don't understand in the Mapping script example why the total CO2 value is not part of the variables listed: is it because it's  at a higher level in the hierarchy that we need to create? Or is it because, it's supposed to be the sum of all the values from the subsector? Or is it because it should be added to the list of subsectors?
> > * In the OWID dataset, there is "trade_co2" which is an interesting variable, as it represents the CO2 emissions linked to commercial exchanges between countries. This helps assess consumption-based CO2 emissions ("consumption_co2"). Should "trade_co2" be one of the subsectors?
> > * Should we also stored results of calculations, or should these calculations be done within the API? For example, "consumption_co2" can be deduced from "co2" and "trade_co2".



> > @S-AI-F
> > @JinqiWANG66
> > A few questions:
> > 
> > * Could you please confirm that the CO2 emissions must be expressed in MtC (and not MtCO2)?
> > * How should we handle values for Kosovo, as the country has no ISO code, as it's not recognized by all countries (cf. https://fr.wikipedia.org/wiki/Kosovo)? In the dataset, the pseudo ISO code is 'OWID_KOS".
> > * I don't understand in the Mapping script example why the total CO2 value is not part of the variables listed: is it because it's  at a higher level in the hierarchy that we need to create? Or is it because, it's supposed to be the sum of all the values from the subsector? Or is it because it should be added to the list of subsectors?
> > * In the OWID dataset, there is "trade_co2" which is an interesting variable, as it represents the CO2 emissions linked to commercial exchanges between countries. This helps assess consumption-based CO2 emissions ("consumption_co2"). Should "trade_co2" be one of the subsectors?
> > * Should we also stored results of calculations, or should these calculations be done within the API? For example, "consumption_co2" can be deduced from "co2" and "trade_co2".

**Comment by S-AI-F** [comment]
@linetonthat 
@JinqiWANG66 

- **units:** Mapped data should keep the same units as data source. We only should mention the unit in the unit filed. So if your dataset is on MtC, you can keep this unit.
- **Kosovo case:** Fiels in json file are not obligatory so if a coun try doesn't have isocode, we don't need to fill or to include the field in the mapped data. If we have a kind of country identifier belonging to the data source, I added a field in the mapped data called "geoComponent_datasource_code" where we can put this information to keep an identifier information somewhere.
- **Total emissions co2** : Total CO2 emissions constitutes one bloc of esmission in mapped data where:
`sector_name: total_emissions`
`gas: CO2 `
- **trade_co2**: Yes, we should keep this interesting variable. We have to check if Trade co2 is a subsector of another sector otherwie, add a sector name called "trade" and put the value there.
- **consumption_co2**: If you have consumption co2 emissions directly in the data source, we can kepp it as is a new sector we may call: "consumption"
- **per capita emissions**: We will not include this variable now, since it will need a new bloc called "emissions per capita" depending on population data. It will be easier to include calculated variables in the future once we have a stable model of raw emissions.

**Comment by linetonthat** [comment]
@S-AI-F 
@JinqiWANG66 

OK, thanks Saif for the feedback. This is clear for me, and I will update the mapping script (probably on Thursday night). Just one question to be sure: 
* We'll define 3 sectors :
list_sectors=["total_emissions","trade","consumption"] 
* We'll define sub-sectors only for sector "total_emissions"
list_subsectors=["cement_co2","coal_co2", "flaring_co2",
                    "gas_co2", "oil_co2", "other_industry_co2"]?

Also, we've made changes in the OGS-mapping Sheet based on this!

**Comment by S-AI-F** [comment]
@linetonthat 
@JinqiWANG66 
I think that mapping rules are not well defined and documented because we should not mix sector and gas in sector fields.
We can discuss the sector definition related to owid data next meeting and to make sure we have aligned data structure between various data sources.
