### ISSUE TITLE
Primap-hist- Mapping with OGS integration data model

### ISSUE THREAD

**Issue by S-AI-F** [OpenGeoScales/ogs-data-exploration#65]
Mapping rules: https://docs.google.com/spreadsheets/d/1CnTpHjZZZepgJ1o1VuQUN61ZaLLRtM1OhZzJU9HCPaY/edit#gid=0

**Comment by S-AI-F** [comment]
@sebastienbourgeois 

### Goal
The goal of this issue consists of testing ogs ghg emissions data model.
Outputs are:
- Filling the excel file for mapping information
- Mapping script
- mapped data in json format

### Mapping information

You are invited to map the dataset you are responsible of with the proposed data model in this file: https://docs.google.com/spreadsheets/d/1CnTpHjZZZepgJ1o1VuQUN61ZaLLRtM1OhZzJU9HCPaY/edit#gid=0

### Mapping script
The mapping script will be stored in **ogs-data-exploration/ghg-emissions/notebooks/your data source name/mapping_datasourcename**
Here is a script example for ammping gcp dataset:
https://github.com/OpenGeoScales/ogs-data-exploration/blob/main/notebooks/ghg-emissions/gcp/Mapping_GCP.ipynb

### Mapped data

Mapped data should be stored as json files in **ogs-data-exploration/ghg-emissions/data/your data source name/mapped/mapped_data_yorudatasourcename**

Here is an example of gcp mapped data: https://github.com/OpenGeoScales/ogs-data-exploration/tree/main/data/ghg-emissions/gcp/mapped

**Comment by sedajeb** [comment]
Hello @S-AI-F,

J'ai mappé les sous-secteurs que je n'avais pas réussi à caser dans une catégorie. J'ai pu en ranger certains dans des catégories finalement et le reste je les ai placés dans "other" comme discuté hier soir. Est-ce que tu peux y jeter un œil et me dire si tout est ok pour toi ?

J'ai remarqué aussi que dans le secteur "energy" de mon dataset, j'ai les sous-secteurs "solid fuels" et "oil and natural gas". Et ils pourraient correspondre aux sous-secteurs mappés "fossil_emissions_coal", "fossil_emissions_gas" et "fossil_emissions_oil" présents dans le secteur mappé "ippu". Cela ne pose-t-il pas problème par rapport aux émissions totales des secteurs et sous-secteurs qui se trouvent dans un autre secteur que celui d'origine ?

Est-ce que je mappe les deux scénarios présents dans le dataset ?

**Comment by S-AI-F** [comment]
Hello @sebastienbourgeois 
Yes je viens de voir l'excel, ça me semble très bien!
Concernant les émission liées fossil fuels, ça ne pose pas de problème pour le moment d'avoir les informations un peu éparpillées sur des champs différents, c'est pareil pour ton secteur "agriculture_excluding_livestock" qui pourrait être lié au secteur "agriculture".
On verra dans un deuxième temps comment on peut rassembler ces infos dans la base de données!
Top sebastien, tu peux attaquer l'étape de génération des données mappées!
Si tu as des questions concernant cette partie tu peux les poser dans le canal ogs-data-integration.
J'ai mis à jour la doc ici: https://github.com/OpenGeoScales/ogs-connectors/wiki/Data-model
Tu as les liens vers le mapping de @bouffan dans le canal. N'hésites pas à ;lui poser des questions  sur son notebook si besoin. Il prend en charge la validation des json générés.
Merci Beaucoup!
