### ISSUE TITLE
UNFCCC- Mapping with OGS integration data model

### ISSUE THREAD

**Issue by S-AI-F** [OpenGeoScales/ogs-data-exploration#69]
Mapping rules: https://docs.google.com/spreadsheets/d/1CnTpHjZZZepgJ1o1VuQUN61ZaLLRtM1OhZzJU9HCPaY/edit#gid=0

**Comment by S-AI-F** [comment]
@lara-krm 

### Goal
The goal of this issue consists of testing ogs ghg emissions data model.
Outputs are:
- Filling the excel file for mapping information
- Mapping script
- mapped data in json format

### Mapping information

You are invited to map the dataset you are responsible of with the proposed data model in this file: https://docs.google.com/spreadsheets/d/1CnTpHjZZZepgJ1o1VuQUN61ZaLLRtM1OhZzJU9HCPaY/edit#gid=0

### Mapping script
The mapping script will be stored in **ogs-data-exploration/ghg-emissions/notebooks/your data source name/mapping_datasourcename**
Here is a script example for ammping gcp dataset:
https://github.com/OpenGeoScales/ogs-data-exploration/blob/main/notebooks/ghg-emissions/gcp/Mapping_GCP.ipynb

### Mapped data

Mapped data should be stored as json files in **ogs-data-exploration/ghg-emissions/data/your data source name/mapped/mapped_data_yorudatasourcename**

Here is an example of gcp mapped data: https://github.com/OpenGeoScales/ogs-data-exploration/tree/main/data/ghg-emissions/gcp/mapped

**Comment by lara-krm** [comment]
@S-AI-F 

With @CJeannesson we have some questions regarding the step "Mapping Information" : 
- "emissions data mapping" sheet : 
• what does "sector_name" and "subsector_name" mean ? Should we specify all the variables we have in the column (all the different sector names) or only the name of the column (ex "Sector") ? 
• regarding the "unit" row, should we mention the name of the column where we have the unit information or should we specify the unit used (ex "MtCO2") ?

- do we have to fill the "sectors mapping" & "sectors-hierarchy" sheets, or only the "sectors mapping" one ?

**Comment by S-AI-F** [comment]
@lara-krm @CJeannesson 
I am sorry that the document was confusing.

- "emissions data mapping" sheet : -You have to fill it only with the column name (for example, "sector" and "unit" columns). I am in discussing with other datasets' responsible to do the same.
- You have to fill only "sector mapping". I will remove the other sheet.

It would be great if you can be available today to discuss quickly the excel in order to answer all your questions before the weekly meeting!

Thanks!

**Comment by S-AI-F** [comment]
@CJeannesson @lara-krm 
@CJeannesson 
Here are the links for updated data model:
- mapping file: https://docs.google.com/spreadsheets/d/1CnTpHjZZZepgJ1o1VuQUN61ZaLLRtM1OhZzJU9HCPaY/edit#gid=2038606787
- doc wiki: https://github.com/OpenGeoScales/ogs-connectors/wiki/Data-model

``` json
{
	"data_source": {
		"name": "unfccc",
		"link": "url",
	},
	"geo_component": {
		"scale": "Country",
		"name": "france",
		"identifier": {
			"id": "FRA",
			"type": "alpha3"
		}
	},
	"date": "2011-01-01",
	"emission": {
		"gas": "co2",
		"value": 624.0,
		"unit": {
			"unit_used": "Mt co2eq"
		},
		"sector":{
			"sector_origin_name": "Total GHG emissions without LULUCF ",
			"sector_mapped_name": "total_excluding_LUCF"
		}
	}
}
```
